# Generated by Django 5.1.6 on 2025-04-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_v20state_alter_voter_v21primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
