# Generated by Django 5.1.6 on 2025-04-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='section',
            name='meeting_days',
        ),
        migrations.RemoveField(
            model_name='section',
            name='start_time',
        ),
    ]
