# Generated by Django 5.1.6 on 2025-04-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_section_end_time_remove_section_meeting_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
    ]
