# Generated by Django 5.1.6 on 2025-04-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinterest',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
